language: rust
sudo: true

before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo sqlite3 -version

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: OnTX/CYuh//CIBBk86aUEQQ+Tg4GRWd7gC9HePxBlKaOOJDCIMzLvhXsjEp7NeYabYttKYYggdO3OqYV9UkEkq39zaQtBPFwp3pBH/DWykX+fvMCBv6NX17ygb6Cij6pGI8DgSx2byLI12xK529yQgci2OrsyVd3sez00mS6hqZ7+2zZZyxhNS+vjXG0u9NBIqz72XBjQFbocjUbn2TJ7jTWAsBW1DwpHsGJQKeTgDKDga28BM7s6OlHsTxfcMfrWBunG41TK6WKKGPVgxR2MM2zWSxAwTgfkqwHvEYaZhsLiXKeMgtlKAj9dt9bPqCEXWih1HWwOiiXy2fXOBDf6NvScHzWNjb86/9cXgiSN6jatw3CYvUyrb22Os3vlZB1Y8mI8NtlbqbHwoNEJmM6gqXD+78mo5TR6ArF+MxUxQOs8t0LXsLu9hX8HKFQvumv4nT4xiqtGalSEfhQPuGlQiSBg9FF4YLd00bOOJyh/HkeMm7HKoCUQiRoORLR2Pg3REOZDqYUbNARKKxoiaelN6CCrTm5dUnHKeOPIJAHhgldAAl3zYhZY7+zRoOU4Dnj9Wc+JNRohL5Z9uPBCzJxjlE//RsExhNUo+NTleSDRz93Q6P9ugQZBxqg3IHs2BcAEri8N/8685mQE9RynG9E+S/TQF3S9YpUoAmZHw99cuU=

notifications:
  email: false
