[package]
name = "database"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/database"
homepage = "https://github.com/hilbert-space/database"
description = "Database."
